spring:
  data:
    redis:
      repositories:
        enabled: false

datasource:
  redis:
    database: 0
    master:
      host: ${REDIS_MASTER_HOST}
      port: ${REDIS_MASTER_PORT}
    replicas:
      - host: ${REDIS_REPLICA_1_HOST}
        port: ${REDIS_REPLICA_1_PORT}

ranking:
  weights:
    like: 0.1
    order: 0.7
    view: 0.2
  ttl: 172800 # 2일(초 단위)
  carry-over-weight: 0.1 # 이전 점수에서 가져올 비율

---
spring.config.activate.on-profile: local, test

datasource:
  redis:
    master:
      host: localhost
      port: 6379
    replicas:
      - host: localhost
        port: 6380

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prd